FROM node:20-slim

ARG TZ=Asia/Jakarta
ARG PORT=4242
ARG POSTGRES_SSL=false
ARG POSTGRES_HOST=0.0.0.0
ARG POSTGRES_PORT=5432
ARG POSTGRES_DATABASE=unleash
ARG POSTGRES_USERNAME=unleash_user
ARG POSTGRES_PASSWORD=password

WORKDIR /app

COPY --chown=node:node . .

ENV NODE_ENV=production

RUN npm install

USER node

ENV TZ=${TZ}
ENV PORT=${PORT}
ENV POSTGRES_SSL=${POSTGRES_SSL}
ENV POSTGRES_HOST=${POSTGRES_HOST}
ENV POSTGRES_PORT=${POSTGRES_PORT}
ENV POSTGRES_DATABASE=${POSTGRES_DATABASE}
ENV POSTGRES_USERNAME=${POSTGRES_USERNAME}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

EXPOSE ${PORT}

CMD ["node", "server.js"]
