name: Benchmark

on:
  push:
    branches:
      - benchmark
  workflow_dispatch:

permissions: write-all

jobs:
  bench:
    name: Benchmark
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.3
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          ref: ${{ github.head_ref }}
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 20
      - name: Install dependencies
        run: npm i
      - name: run bench.setup.sh
        run: |
          chmod +x bench.setup.sh
          ./bench.setup.sh
      - name: run bench.sh
        run: |
          chmod +x bench.sh
          ./bench.sh
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
